$engine: 3
$onesync: on
$minFxVersion: 7290

name: FluviaRP
version: 1.0.0
author: NobleMP4

tasks:
  - action: download_github
    src: https://github.com/NobleMP4/FluviaRP
    ref: main
    dest: ./fluvia_tmp

  - action: move_path
    src: ./fluvia_tmp/resources
    dest: ./resources

  - action: move_path
    src: ./fluvia_tmp/server.cfg
    dest: ./server.cfg

  - action: remove_path
    path: ./fluvia_tmp